// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Bankingpb/Golang-gRPC-Banking.proto

package Golang_gRPC_Banking

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateAccountRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,3,opt,name=PhoneNumber,proto3" json:"PhoneNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountRequest) Reset()         { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()    {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2125a343f0ee38f2, []int{0}
}

func (m *CreateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountRequest.Unmarshal(m, b)
}
func (m *CreateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountRequest.Marshal(b, m, deterministic)
}
func (m *CreateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountRequest.Merge(m, src)
}
func (m *CreateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAccountRequest.Size(m)
}
func (m *CreateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountRequest proto.InternalMessageInfo

func (m *CreateAccountRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateAccountRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateAccountRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type CreateAccountResponse struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountResponse) Reset()         { *m = CreateAccountResponse{} }
func (m *CreateAccountResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAccountResponse) ProtoMessage()    {}
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2125a343f0ee38f2, []int{1}
}

func (m *CreateAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountResponse.Unmarshal(m, b)
}
func (m *CreateAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountResponse.Marshal(b, m, deterministic)
}
func (m *CreateAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountResponse.Merge(m, src)
}
func (m *CreateAccountResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAccountResponse.Size(m)
}
func (m *CreateAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountResponse proto.InternalMessageInfo

func (m *CreateAccountResponse) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

type ReadAccountRequest struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadAccountRequest) Reset()         { *m = ReadAccountRequest{} }
func (m *ReadAccountRequest) String() string { return proto.CompactTextString(m) }
func (*ReadAccountRequest) ProtoMessage()    {}
func (*ReadAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2125a343f0ee38f2, []int{2}
}

func (m *ReadAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAccountRequest.Unmarshal(m, b)
}
func (m *ReadAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAccountRequest.Marshal(b, m, deterministic)
}
func (m *ReadAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAccountRequest.Merge(m, src)
}
func (m *ReadAccountRequest) XXX_Size() int {
	return xxx_messageInfo_ReadAccountRequest.Size(m)
}
func (m *ReadAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAccountRequest proto.InternalMessageInfo

func (m *ReadAccountRequest) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

type ReadAccountResponse struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,4,opt,name=PhoneNumber,proto3" json:"PhoneNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadAccountResponse) Reset()         { *m = ReadAccountResponse{} }
func (m *ReadAccountResponse) String() string { return proto.CompactTextString(m) }
func (*ReadAccountResponse) ProtoMessage()    {}
func (*ReadAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2125a343f0ee38f2, []int{3}
}

func (m *ReadAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAccountResponse.Unmarshal(m, b)
}
func (m *ReadAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAccountResponse.Marshal(b, m, deterministic)
}
func (m *ReadAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAccountResponse.Merge(m, src)
}
func (m *ReadAccountResponse) XXX_Size() int {
	return xxx_messageInfo_ReadAccountResponse.Size(m)
}
func (m *ReadAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAccountResponse proto.InternalMessageInfo

func (m *ReadAccountResponse) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *ReadAccountResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReadAccountResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ReadAccountResponse) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type DepositMoneyRequest struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Money                int64    `protobuf:"varint,2,opt,name=Money,proto3" json:"Money,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DepositMoneyRequest) Reset()         { *m = DepositMoneyRequest{} }
func (m *DepositMoneyRequest) String() string { return proto.CompactTextString(m) }
func (*DepositMoneyRequest) ProtoMessage()    {}
func (*DepositMoneyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2125a343f0ee38f2, []int{4}
}

func (m *DepositMoneyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepositMoneyRequest.Unmarshal(m, b)
}
func (m *DepositMoneyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepositMoneyRequest.Marshal(b, m, deterministic)
}
func (m *DepositMoneyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepositMoneyRequest.Merge(m, src)
}
func (m *DepositMoneyRequest) XXX_Size() int {
	return xxx_messageInfo_DepositMoneyRequest.Size(m)
}
func (m *DepositMoneyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DepositMoneyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DepositMoneyRequest proto.InternalMessageInfo

func (m *DepositMoneyRequest) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *DepositMoneyRequest) GetMoney() int64 {
	if m != nil {
		return m.Money
	}
	return 0
}

type DepositMoneyResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DepositMoneyResponse) Reset()         { *m = DepositMoneyResponse{} }
func (m *DepositMoneyResponse) String() string { return proto.CompactTextString(m) }
func (*DepositMoneyResponse) ProtoMessage()    {}
func (*DepositMoneyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2125a343f0ee38f2, []int{5}
}

func (m *DepositMoneyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepositMoneyResponse.Unmarshal(m, b)
}
func (m *DepositMoneyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepositMoneyResponse.Marshal(b, m, deterministic)
}
func (m *DepositMoneyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepositMoneyResponse.Merge(m, src)
}
func (m *DepositMoneyResponse) XXX_Size() int {
	return xxx_messageInfo_DepositMoneyResponse.Size(m)
}
func (m *DepositMoneyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DepositMoneyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DepositMoneyResponse proto.InternalMessageInfo

func (m *DepositMoneyResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type WithdrawMoneyRequest struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Money                int64    `protobuf:"varint,2,opt,name=Money,proto3" json:"Money,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithdrawMoneyRequest) Reset()         { *m = WithdrawMoneyRequest{} }
func (m *WithdrawMoneyRequest) String() string { return proto.CompactTextString(m) }
func (*WithdrawMoneyRequest) ProtoMessage()    {}
func (*WithdrawMoneyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2125a343f0ee38f2, []int{6}
}

func (m *WithdrawMoneyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawMoneyRequest.Unmarshal(m, b)
}
func (m *WithdrawMoneyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawMoneyRequest.Marshal(b, m, deterministic)
}
func (m *WithdrawMoneyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawMoneyRequest.Merge(m, src)
}
func (m *WithdrawMoneyRequest) XXX_Size() int {
	return xxx_messageInfo_WithdrawMoneyRequest.Size(m)
}
func (m *WithdrawMoneyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawMoneyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawMoneyRequest proto.InternalMessageInfo

func (m *WithdrawMoneyRequest) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *WithdrawMoneyRequest) GetMoney() int64 {
	if m != nil {
		return m.Money
	}
	return 0
}

type WithdrawMoneyResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithdrawMoneyResponse) Reset()         { *m = WithdrawMoneyResponse{} }
func (m *WithdrawMoneyResponse) String() string { return proto.CompactTextString(m) }
func (*WithdrawMoneyResponse) ProtoMessage()    {}
func (*WithdrawMoneyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2125a343f0ee38f2, []int{7}
}

func (m *WithdrawMoneyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawMoneyResponse.Unmarshal(m, b)
}
func (m *WithdrawMoneyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawMoneyResponse.Marshal(b, m, deterministic)
}
func (m *WithdrawMoneyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawMoneyResponse.Merge(m, src)
}
func (m *WithdrawMoneyResponse) XXX_Size() int {
	return xxx_messageInfo_WithdrawMoneyResponse.Size(m)
}
func (m *WithdrawMoneyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawMoneyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawMoneyResponse proto.InternalMessageInfo

func (m *WithdrawMoneyResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateAccountRequest)(nil), "rGPC_Banking.CreateAccountRequest")
	proto.RegisterType((*CreateAccountResponse)(nil), "rGPC_Banking.CreateAccountResponse")
	proto.RegisterType((*ReadAccountRequest)(nil), "rGPC_Banking.ReadAccountRequest")
	proto.RegisterType((*ReadAccountResponse)(nil), "rGPC_Banking.ReadAccountResponse")
	proto.RegisterType((*DepositMoneyRequest)(nil), "rGPC_Banking.DepositMoneyRequest")
	proto.RegisterType((*DepositMoneyResponse)(nil), "rGPC_Banking.DepositMoneyResponse")
	proto.RegisterType((*WithdrawMoneyRequest)(nil), "rGPC_Banking.WithdrawMoneyRequest")
	proto.RegisterType((*WithdrawMoneyResponse)(nil), "rGPC_Banking.WithdrawMoneyResponse")
}

func init() {
	proto.RegisterFile("Bankingpb/Golang-gRPC-Banking.proto", fileDescriptor_2125a343f0ee38f2)
}

var fileDescriptor_2125a343f0ee38f2 = []byte{
	// 437 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xc1, 0xaa, 0xd3, 0x40,
	0x14, 0xa5, 0xc9, 0x7b, 0x0f, 0xbc, 0xef, 0xb5, 0xc2, 0x34, 0x95, 0x1a, 0x5c, 0xd4, 0x79, 0xa2,
	0x0f, 0xe1, 0x65, 0xa0, 0xe2, 0x46, 0xdd, 0xd8, 0x46, 0x4a, 0x17, 0x96, 0x12, 0x11, 0xc5, 0x8d,
	0x4c, 0xd2, 0x21, 0x1d, 0x4c, 0x66, 0xd2, 0x64, 0xa2, 0x88, 0xb8, 0xf1, 0x17, 0xfc, 0x02, 0xbf,
	0xc9, 0x5f, 0xf0, 0x43, 0xc4, 0xc9, 0x20, 0x49, 0x1a, 0xb3, 0x70, 0xd7, 0x7b, 0xef, 0x99, 0x7b,
	0xee, 0x3d, 0xe7, 0x36, 0x70, 0xb9, 0xa0, 0xe2, 0x03, 0x17, 0x71, 0x16, 0x92, 0x95, 0x4c, 0xa8,
	0x88, 0xaf, 0xe3, 0x60, 0xbb, 0xbc, 0x36, 0x59, 0x2f, 0xcb, 0xa5, 0x92, 0xe8, 0x22, 0x5f, 0x6d,
	0x97, 0xef, 0x4d, 0xce, 0xbd, 0x13, 0x4b, 0x19, 0x27, 0x8c, 0xd0, 0x8c, 0x13, 0x2a, 0x84, 0x54,
	0x54, 0x71, 0x29, 0x8a, 0x0a, 0x8b, 0x43, 0x70, 0x96, 0x39, 0xa3, 0x8a, 0x3d, 0x8f, 0x22, 0x59,
	0x0a, 0x15, 0xb0, 0x43, 0xc9, 0x0a, 0x85, 0x10, 0x9c, 0x6c, 0x68, 0xca, 0xa6, 0x83, 0xd9, 0xe0,
	0xea, 0x46, 0xa0, 0x7f, 0x23, 0x07, 0x4e, 0x5f, 0xa4, 0x94, 0x27, 0x53, 0x4b, 0x27, 0xab, 0x00,
	0xcd, 0xe0, 0x7c, 0xbb, 0x97, 0x82, 0x6d, 0xca, 0x34, 0x64, 0xf9, 0xd4, 0xd6, 0xb5, 0x7a, 0x0a,
	0x3f, 0x80, 0x49, 0x8b, 0xa3, 0xc8, 0xa4, 0x28, 0x18, 0x1a, 0x81, 0xb5, 0xf6, 0x35, 0xc5, 0x69,
	0x60, 0xad, 0x7d, 0x7c, 0x0f, 0x50, 0xc0, 0xe8, 0xae, 0x35, 0x4a, 0x1b, 0x75, 0x80, 0x71, 0x03,
	0xd5, 0xdd, 0xec, 0xef, 0x06, 0x56, 0xd7, 0x06, 0x76, 0xcf, 0x06, 0x27, 0xc7, 0x1b, 0x3c, 0x85,
	0xb1, 0xcf, 0x32, 0x59, 0x70, 0xf5, 0x52, 0x0a, 0xf6, 0xf9, 0x1f, 0x93, 0xfd, 0x69, 0xaf, 0xeb,
	0x9a, 0xd3, 0x0e, 0xaa, 0x00, 0x7b, 0xe0, 0x34, 0x1f, 0x9b, 0x81, 0x6f, 0xc1, 0x59, 0xc0, 0x8a,
	0x32, 0x51, 0x46, 0x64, 0x13, 0xe1, 0x67, 0xe0, 0xbc, 0xe1, 0x6a, 0xbf, 0xcb, 0xe9, 0xa7, 0xff,
	0x60, 0x23, 0x30, 0x69, 0xbd, 0xee, 0xa7, 0x9b, 0xff, 0xb0, 0x61, 0x64, 0x6e, 0xe5, 0x15, 0xcb,
	0x3f, 0xf2, 0x88, 0xa1, 0x02, 0x86, 0x0d, 0xc3, 0x10, 0xf6, 0xea, 0x27, 0xe5, 0x75, 0x5d, 0x8c,
	0x7b, 0xd9, 0x8b, 0xa9, 0x86, 0xc0, 0xb7, 0xbf, 0xfd, 0xfc, 0xf5, 0xdd, 0x1a, 0xe3, 0x11, 0x69,
	0xd4, 0x9f, 0x0c, 0x1e, 0x22, 0x0e, 0xe7, 0x35, 0x5b, 0xd1, 0xac, 0xd9, 0xee, 0xf8, 0x2e, 0xdc,
	0xbb, 0x3d, 0x08, 0x43, 0x37, 0xd1, 0x74, 0x37, 0xd1, 0x90, 0x98, 0x0a, 0xf9, 0xb2, 0xf6, 0xbf,
	0xa2, 0xd7, 0x70, 0x51, 0x77, 0x04, 0xb5, 0x3a, 0x75, 0x58, 0xed, 0xe2, 0x3e, 0x88, 0x51, 0xf8,
	0x2d, 0x0c, 0x1b, 0xd2, 0xb7, 0x65, 0xeb, 0x72, 0xb5, 0x2d, 0x5b, 0xa7, 0x77, 0x8b, 0xab, 0x77,
	0xf7, 0x63, 0xae, 0xf6, 0x65, 0xe8, 0x45, 0x32, 0x25, 0x3b, 0x2a, 0xe2, 0xf9, 0xe3, 0x79, 0xd7,
	0x17, 0x20, 0x3c, 0xd3, 0x7f, 0xeb, 0x47, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xc6, 0x49, 0x0c,
	0x69, 0x29, 0x04, 0x00, 0x00,
}
