// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: Bankingpb/Golang-gRPC-Banking.proto

package Golang_gRPC_Banking

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAccountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Email       string `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	PhoneNumber string `protobuf:"bytes,3,opt,name=PhoneNumber,proto3" json:"PhoneNumber,omitempty"`
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_Bankingpb_Golang_gRPC_Banking_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAccountRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAccountRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateAccountRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type CreateAccountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int32 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_Bankingpb_Golang_gRPC_Banking_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAccountResponse) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

type ReadAccountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int32 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *ReadAccountRequest) Reset() {
	*x = ReadAccountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAccountRequest) ProtoMessage() {}

func (x *ReadAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAccountRequest.ProtoReflect.Descriptor instead.
func (*ReadAccountRequest) Descriptor() ([]byte, []int) {
	return file_Bankingpb_Golang_gRPC_Banking_proto_rawDescGZIP(), []int{2}
}

func (x *ReadAccountRequest) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

type ReadAccountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID          int32  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Email       string `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	PhoneNumber string `protobuf:"bytes,4,opt,name=PhoneNumber,proto3" json:"PhoneNumber,omitempty"`
}

func (x *ReadAccountResponse) Reset() {
	*x = ReadAccountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAccountResponse) ProtoMessage() {}

func (x *ReadAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAccountResponse.ProtoReflect.Descriptor instead.
func (*ReadAccountResponse) Descriptor() ([]byte, []int) {
	return file_Bankingpb_Golang_gRPC_Banking_proto_rawDescGZIP(), []int{3}
}

func (x *ReadAccountResponse) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *ReadAccountResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReadAccountResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ReadAccountResponse) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type DepositMoneyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID    int32 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Money int64 `protobuf:"varint,2,opt,name=Money,proto3" json:"Money,omitempty"`
}

func (x *DepositMoneyRequest) Reset() {
	*x = DepositMoneyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositMoneyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositMoneyRequest) ProtoMessage() {}

func (x *DepositMoneyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositMoneyRequest.ProtoReflect.Descriptor instead.
func (*DepositMoneyRequest) Descriptor() ([]byte, []int) {
	return file_Bankingpb_Golang_gRPC_Banking_proto_rawDescGZIP(), []int{4}
}

func (x *DepositMoneyRequest) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *DepositMoneyRequest) GetMoney() int64 {
	if x != nil {
		return x.Money
	}
	return 0
}

type DepositMoneyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
}

func (x *DepositMoneyResponse) Reset() {
	*x = DepositMoneyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositMoneyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositMoneyResponse) ProtoMessage() {}

func (x *DepositMoneyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositMoneyResponse.ProtoReflect.Descriptor instead.
func (*DepositMoneyResponse) Descriptor() ([]byte, []int) {
	return file_Bankingpb_Golang_gRPC_Banking_proto_rawDescGZIP(), []int{5}
}

func (x *DepositMoneyResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type WithdrawMoneyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID    int32 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Money int64 `protobuf:"varint,2,opt,name=Money,proto3" json:"Money,omitempty"`
}

func (x *WithdrawMoneyRequest) Reset() {
	*x = WithdrawMoneyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithdrawMoneyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawMoneyRequest) ProtoMessage() {}

func (x *WithdrawMoneyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawMoneyRequest.ProtoReflect.Descriptor instead.
func (*WithdrawMoneyRequest) Descriptor() ([]byte, []int) {
	return file_Bankingpb_Golang_gRPC_Banking_proto_rawDescGZIP(), []int{6}
}

func (x *WithdrawMoneyRequest) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *WithdrawMoneyRequest) GetMoney() int64 {
	if x != nil {
		return x.Money
	}
	return 0
}

type WithdrawMoneyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
}

func (x *WithdrawMoneyResponse) Reset() {
	*x = WithdrawMoneyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithdrawMoneyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawMoneyResponse) ProtoMessage() {}

func (x *WithdrawMoneyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawMoneyResponse.ProtoReflect.Descriptor instead.
func (*WithdrawMoneyResponse) Descriptor() ([]byte, []int) {
	return file_Bankingpb_Golang_gRPC_Banking_proto_rawDescGZIP(), []int{7}
}

func (x *WithdrawMoneyResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_Bankingpb_Golang_gRPC_Banking_proto protoreflect.FileDescriptor

var file_Bankingpb_Golang_gRPC_Banking_proto_rawDesc = []byte{
	0x0a, 0x23, 0x42, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x70, 0x62, 0x2f, 0x47, 0x6f, 0x6c, 0x61,
	0x6e, 0x67, 0x2d, 0x67, 0x52, 0x50, 0x43, 0x2d, 0x42, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x72, 0x47, 0x50, 0x43, 0x5f, 0x42, 0x61, 0x6e, 0x6b,
	0x69, 0x6e, 0x67, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x62, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x27, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x44, 0x22, 0x24,
	0x0a, 0x12, 0x52, 0x65, 0x61, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x49, 0x44, 0x22, 0x71, 0x0a, 0x13, 0x52, 0x65, 0x61, 0x64, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x50, 0x68, 0x6f, 0x6e,
	0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x3b, 0x0a, 0x13, 0x44, 0x65, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x44, 0x12, 0x14,
	0x0a, 0x05, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x4d,
	0x6f, 0x6e, 0x65, 0x79, 0x22, 0x2e, 0x0a, 0x14, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x4d,
	0x6f, 0x6e, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x22, 0x3c, 0x0a, 0x14, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77,
	0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05,
	0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x4d, 0x6f, 0x6e,
	0x65, 0x79, 0x22, 0x2f, 0x0a, 0x15, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x4d, 0x6f,
	0x6e, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x32, 0xa1, 0x03, 0x0a, 0x0e, 0x42, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x73, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x22, 0x2e, 0x72, 0x47, 0x50, 0x43, 0x5f, 0x42,
	0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x72, 0x47,
	0x50, 0x43, 0x5f, 0x42, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x19, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x13, 0x22, 0x0e, 0x2f, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x3a, 0x01, 0x2a, 0x12, 0x69, 0x0a, 0x0b, 0x52,
	0x65, 0x61, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x20, 0x2e, 0x72, 0x47, 0x50,
	0x43, 0x5f, 0x42, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x72,
	0x47, 0x50, 0x43, 0x5f, 0x42, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x65, 0x61, 0x64,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f, 0x12, 0x0d, 0x2f, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x2f, 0x7b, 0x49, 0x44, 0x7d, 0x12, 0x55, 0x0a, 0x0c, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x12, 0x21, 0x2e, 0x72, 0x47, 0x50, 0x43, 0x5f, 0x42, 0x61,
	0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x4d, 0x6f, 0x6e,
	0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x72, 0x47, 0x50, 0x43,
	0x5f, 0x42, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x58, 0x0a,
	0x0d, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x12, 0x22,
	0x2e, 0x72, 0x47, 0x50, 0x43, 0x5f, 0x42, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x57, 0x69,
	0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x23, 0x2e, 0x72, 0x47, 0x50, 0x43, 0x5f, 0x42, 0x61, 0x6e, 0x6b, 0x69, 0x6e,
	0x67, 0x2e, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x61, 0x6e, 0x67, 0x32, 0x35, 0x32, 0x2f, 0x47, 0x6f,
	0x6c, 0x61, 0x6e, 0x67, 0x2d, 0x67, 0x52, 0x50, 0x43, 0x2d, 0x42, 0x61, 0x6e, 0x6b, 0x69, 0x6e,
	0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Bankingpb_Golang_gRPC_Banking_proto_rawDescOnce sync.Once
	file_Bankingpb_Golang_gRPC_Banking_proto_rawDescData = file_Bankingpb_Golang_gRPC_Banking_proto_rawDesc
)

func file_Bankingpb_Golang_gRPC_Banking_proto_rawDescGZIP() []byte {
	file_Bankingpb_Golang_gRPC_Banking_proto_rawDescOnce.Do(func() {
		file_Bankingpb_Golang_gRPC_Banking_proto_rawDescData = protoimpl.X.CompressGZIP(file_Bankingpb_Golang_gRPC_Banking_proto_rawDescData)
	})
	return file_Bankingpb_Golang_gRPC_Banking_proto_rawDescData
}

var file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_Bankingpb_Golang_gRPC_Banking_proto_goTypes = []interface{}{
	(*CreateAccountRequest)(nil),  // 0: rGPC_Banking.CreateAccountRequest
	(*CreateAccountResponse)(nil), // 1: rGPC_Banking.CreateAccountResponse
	(*ReadAccountRequest)(nil),    // 2: rGPC_Banking.ReadAccountRequest
	(*ReadAccountResponse)(nil),   // 3: rGPC_Banking.ReadAccountResponse
	(*DepositMoneyRequest)(nil),   // 4: rGPC_Banking.DepositMoneyRequest
	(*DepositMoneyResponse)(nil),  // 5: rGPC_Banking.DepositMoneyResponse
	(*WithdrawMoneyRequest)(nil),  // 6: rGPC_Banking.WithdrawMoneyRequest
	(*WithdrawMoneyResponse)(nil), // 7: rGPC_Banking.WithdrawMoneyResponse
}
var file_Bankingpb_Golang_gRPC_Banking_proto_depIdxs = []int32{
	0, // 0: rGPC_Banking.BankingService.CreateAccount:input_type -> rGPC_Banking.CreateAccountRequest
	2, // 1: rGPC_Banking.BankingService.ReadAccount:input_type -> rGPC_Banking.ReadAccountRequest
	4, // 2: rGPC_Banking.BankingService.DepositMoney:input_type -> rGPC_Banking.DepositMoneyRequest
	6, // 3: rGPC_Banking.BankingService.WithdrawMoney:input_type -> rGPC_Banking.WithdrawMoneyRequest
	1, // 4: rGPC_Banking.BankingService.CreateAccount:output_type -> rGPC_Banking.CreateAccountResponse
	3, // 5: rGPC_Banking.BankingService.ReadAccount:output_type -> rGPC_Banking.ReadAccountResponse
	5, // 6: rGPC_Banking.BankingService.DepositMoney:output_type -> rGPC_Banking.DepositMoneyResponse
	7, // 7: rGPC_Banking.BankingService.WithdrawMoney:output_type -> rGPC_Banking.WithdrawMoneyResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Bankingpb_Golang_gRPC_Banking_proto_init() }
func file_Bankingpb_Golang_gRPC_Banking_proto_init() {
	if File_Bankingpb_Golang_gRPC_Banking_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAccountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAccountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadAccountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadAccountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositMoneyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositMoneyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithdrawMoneyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithdrawMoneyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Bankingpb_Golang_gRPC_Banking_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Bankingpb_Golang_gRPC_Banking_proto_goTypes,
		DependencyIndexes: file_Bankingpb_Golang_gRPC_Banking_proto_depIdxs,
		MessageInfos:      file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes,
	}.Build()
	File_Bankingpb_Golang_gRPC_Banking_proto = out.File
	file_Bankingpb_Golang_gRPC_Banking_proto_rawDesc = nil
	file_Bankingpb_Golang_gRPC_Banking_proto_goTypes = nil
	file_Bankingpb_Golang_gRPC_Banking_proto_depIdxs = nil
}
