// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: Bankingpb/Golang-gRPC-Banking.proto

package Golang_gRPC_Banking

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email       string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber string `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_Bankingpb_Golang_gRPC_Banking_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_Bankingpb_Golang_gRPC_Banking_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ReadUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ReadUserRequest) Reset() {
	*x = ReadUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadUserRequest) ProtoMessage() {}

func (x *ReadUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadUserRequest.ProtoReflect.Descriptor instead.
func (*ReadUserRequest) Descriptor() ([]byte, []int) {
	return file_Bankingpb_Golang_gRPC_Banking_proto_rawDescGZIP(), []int{2}
}

func (x *ReadUserRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ReadUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email       string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber string `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
}

func (x *ReadUserResponse) Reset() {
	*x = ReadUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadUserResponse) ProtoMessage() {}

func (x *ReadUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadUserResponse.ProtoReflect.Descriptor instead.
func (*ReadUserResponse) Descriptor() ([]byte, []int) {
	return file_Bankingpb_Golang_gRPC_Banking_proto_rawDescGZIP(), []int{3}
}

func (x *ReadUserResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReadUserResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReadUserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ReadUserResponse) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type CreateBankAccountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  int32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Balance int64 `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
}

func (x *CreateBankAccountRequest) Reset() {
	*x = CreateBankAccountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBankAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBankAccountRequest) ProtoMessage() {}

func (x *CreateBankAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBankAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateBankAccountRequest) Descriptor() ([]byte, []int) {
	return file_Bankingpb_Golang_gRPC_Banking_proto_rawDescGZIP(), []int{4}
}

func (x *CreateBankAccountRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateBankAccountRequest) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type CreateBankAccountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateBankAccountResponse) Reset() {
	*x = CreateBankAccountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBankAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBankAccountResponse) ProtoMessage() {}

func (x *CreateBankAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBankAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateBankAccountResponse) Descriptor() ([]byte, []int) {
	return file_Bankingpb_Golang_gRPC_Banking_proto_rawDescGZIP(), []int{5}
}

func (x *CreateBankAccountResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DepositMoneyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Money int64 `protobuf:"varint,2,opt,name=money,proto3" json:"money,omitempty"`
}

func (x *DepositMoneyRequest) Reset() {
	*x = DepositMoneyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositMoneyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositMoneyRequest) ProtoMessage() {}

func (x *DepositMoneyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositMoneyRequest.ProtoReflect.Descriptor instead.
func (*DepositMoneyRequest) Descriptor() ([]byte, []int) {
	return file_Bankingpb_Golang_gRPC_Banking_proto_rawDescGZIP(), []int{6}
}

func (x *DepositMoneyRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DepositMoneyRequest) GetMoney() int64 {
	if x != nil {
		return x.Money
	}
	return 0
}

type DepositMoneyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *DepositMoneyResponse) Reset() {
	*x = DepositMoneyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositMoneyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositMoneyResponse) ProtoMessage() {}

func (x *DepositMoneyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositMoneyResponse.ProtoReflect.Descriptor instead.
func (*DepositMoneyResponse) Descriptor() ([]byte, []int) {
	return file_Bankingpb_Golang_gRPC_Banking_proto_rawDescGZIP(), []int{7}
}

func (x *DepositMoneyResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type WithdrawMoneyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Money int64 `protobuf:"varint,2,opt,name=money,proto3" json:"money,omitempty"`
}

func (x *WithdrawMoneyRequest) Reset() {
	*x = WithdrawMoneyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithdrawMoneyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawMoneyRequest) ProtoMessage() {}

func (x *WithdrawMoneyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawMoneyRequest.ProtoReflect.Descriptor instead.
func (*WithdrawMoneyRequest) Descriptor() ([]byte, []int) {
	return file_Bankingpb_Golang_gRPC_Banking_proto_rawDescGZIP(), []int{8}
}

func (x *WithdrawMoneyRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WithdrawMoneyRequest) GetMoney() int64 {
	if x != nil {
		return x.Money
	}
	return 0
}

type WithdrawMoneyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *WithdrawMoneyResponse) Reset() {
	*x = WithdrawMoneyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithdrawMoneyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawMoneyResponse) ProtoMessage() {}

func (x *WithdrawMoneyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawMoneyResponse.ProtoReflect.Descriptor instead.
func (*WithdrawMoneyResponse) Descriptor() ([]byte, []int) {
	return file_Bankingpb_Golang_gRPC_Banking_proto_rawDescGZIP(), []int{9}
}

func (x *WithdrawMoneyResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type EmptyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_Bankingpb_Golang_gRPC_Banking_proto_rawDescGZIP(), []int{10}
}

type BankAccountReportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId int32 `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
}

func (x *BankAccountReportRequest) Reset() {
	*x = BankAccountReportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BankAccountReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankAccountReportRequest) ProtoMessage() {}

func (x *BankAccountReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankAccountReportRequest.ProtoReflect.Descriptor instead.
func (*BankAccountReportRequest) Descriptor() ([]byte, []int) {
	return file_Bankingpb_Golang_gRPC_Banking_proto_rawDescGZIP(), []int{11}
}

func (x *BankAccountReportRequest) GetAccountId() int32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

type BankAccountReportResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId     int32    `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Transactions  []string `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`
	TotalDeposit  int64    `protobuf:"varint,3,opt,name=total_deposit,json=totalDeposit,proto3" json:"total_deposit,omitempty"`
	TotalWithdraw int64    `protobuf:"varint,4,opt,name=total_withdraw,json=totalWithdraw,proto3" json:"total_withdraw,omitempty"`
}

func (x *BankAccountReportResponse) Reset() {
	*x = BankAccountReportResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BankAccountReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankAccountReportResponse) ProtoMessage() {}

func (x *BankAccountReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankAccountReportResponse.ProtoReflect.Descriptor instead.
func (*BankAccountReportResponse) Descriptor() ([]byte, []int) {
	return file_Bankingpb_Golang_gRPC_Banking_proto_rawDescGZIP(), []int{12}
}

func (x *BankAccountReportResponse) GetAccountId() int32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *BankAccountReportResponse) GetTransactions() []string {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *BankAccountReportResponse) GetTotalDeposit() int64 {
	if x != nil {
		return x.TotalDeposit
	}
	return 0
}

func (x *BankAccountReportResponse) GetTotalWithdraw() int64 {
	if x != nil {
		return x.TotalWithdraw
	}
	return 0
}

type AllAccountReportResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BankAccountReport []*BankAccountReportResponse `protobuf:"bytes,1,rep,name=bank_account_report,json=bankAccountReport,proto3" json:"bank_account_report,omitempty"`
}

func (x *AllAccountReportResponse) Reset() {
	*x = AllAccountReportResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllAccountReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllAccountReportResponse) ProtoMessage() {}

func (x *AllAccountReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllAccountReportResponse.ProtoReflect.Descriptor instead.
func (*AllAccountReportResponse) Descriptor() ([]byte, []int) {
	return file_Bankingpb_Golang_gRPC_Banking_proto_rawDescGZIP(), []int{13}
}

func (x *AllAccountReportResponse) GetBankAccountReport() []*BankAccountReportResponse {
	if x != nil {
		return x.BankAccountReport
	}
	return nil
}

type UserReportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UserReportRequest) Reset() {
	*x = UserReportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReportRequest) ProtoMessage() {}

func (x *UserReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReportRequest.ProtoReflect.Descriptor instead.
func (*UserReportRequest) Descriptor() ([]byte, []int) {
	return file_Bankingpb_Golang_gRPC_Banking_proto_rawDescGZIP(), []int{14}
}

func (x *UserReportRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UserReportResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message           string                       `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	BankAccountReport []*BankAccountReportResponse `protobuf:"bytes,2,rep,name=bank_account_report,json=bankAccountReport,proto3" json:"bank_account_report,omitempty"`
}

func (x *UserReportResponse) Reset() {
	*x = UserReportResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReportResponse) ProtoMessage() {}

func (x *UserReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReportResponse.ProtoReflect.Descriptor instead.
func (*UserReportResponse) Descriptor() ([]byte, []int) {
	return file_Bankingpb_Golang_gRPC_Banking_proto_rawDescGZIP(), []int{15}
}

func (x *UserReportResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UserReportResponse) GetBankAccountReport() []*BankAccountReportResponse {
	if x != nil {
		return x.BankAccountReport
	}
	return nil
}

type GetUserAllAccountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetUserAllAccountRequest) Reset() {
	*x = GetUserAllAccountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserAllAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAllAccountRequest) ProtoMessage() {}

func (x *GetUserAllAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAllAccountRequest.ProtoReflect.Descriptor instead.
func (*GetUserAllAccountRequest) Descriptor() ([]byte, []int) {
	return file_Bankingpb_Golang_gRPC_Banking_proto_rawDescGZIP(), []int{16}
}

func (x *GetUserAllAccountRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUserAllAccountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BankAccountIds []int32 `protobuf:"varint,1,rep,packed,name=bank_account_ids,json=bankAccountIds,proto3" json:"bank_account_ids,omitempty"`
}

func (x *GetUserAllAccountResponse) Reset() {
	*x = GetUserAllAccountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserAllAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAllAccountResponse) ProtoMessage() {}

func (x *GetUserAllAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAllAccountResponse.ProtoReflect.Descriptor instead.
func (*GetUserAllAccountResponse) Descriptor() ([]byte, []int) {
	return file_Bankingpb_Golang_gRPC_Banking_proto_rawDescGZIP(), []int{17}
}

func (x *GetUserAllAccountResponse) GetBankAccountIds() []int32 {
	if x != nil {
		return x.BankAccountIds
	}
	return nil
}

var File_Bankingpb_Golang_gRPC_Banking_proto protoreflect.FileDescriptor

var file_Bankingpb_Golang_gRPC_Banking_proto_rawDesc = []byte{
	0x0a, 0x23, 0x42, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x70, 0x62, 0x2f, 0x47, 0x6f, 0x6c, 0x61,
	0x6e, 0x67, 0x2d, 0x67, 0x52, 0x50, 0x43, 0x2d, 0x42, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x72, 0x47, 0x50, 0x43, 0x5f, 0x42, 0x61, 0x6e, 0x6b,
	0x69, 0x6e, 0x67, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x60, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x12, 0x21, 0x0a, 0x0c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x22, 0x24, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x21, 0x0a, 0x0f, 0x52, 0x65, 0x61,
	0x64, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x6f, 0x0a, 0x10,
	0x52, 0x65, 0x61, 0x64, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x68,
	0x6f, 0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x4d, 0x0a,
	0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x6e, 0x6b, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x2b, 0x0a, 0x19,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x6e, 0x6b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3b, 0x0a, 0x13, 0x44, 0x65, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x22, 0x2e, 0x0a, 0x14, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x3c, 0x0a, 0x14, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72,
	0x61, 0x77, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6d,
	0x6f, 0x6e, 0x65, 0x79, 0x22, 0x2f, 0x0a, 0x15, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77,
	0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x39, 0x0a, 0x18, 0x42, 0x61, 0x6e, 0x6b, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64,
	0x22, 0xaa, 0x01, 0x0a, 0x19, 0x42, 0x61, 0x6e, 0x6b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x22, 0x0a,
	0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x64, 0x65, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x44,
	0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f,
	0x77, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x22, 0x73, 0x0a,
	0x18, 0x41, 0x6c, 0x6c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x57, 0x0a, 0x13, 0x62, 0x61, 0x6e,
	0x6b, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x72, 0x47, 0x50, 0x43, 0x5f, 0x42, 0x61,
	0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x42, 0x61, 0x6e, 0x6b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52,
	0x11, 0x62, 0x61, 0x6e, 0x6b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x22, 0x23, 0x0a, 0x11, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x87, 0x01, 0x0a, 0x12, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x57, 0x0a, 0x13, 0x62, 0x61, 0x6e, 0x6b,
	0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x72, 0x47, 0x50, 0x43, 0x5f, 0x42, 0x61, 0x6e,
	0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x42, 0x61, 0x6e, 0x6b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x11,
	0x62, 0x61, 0x6e, 0x6b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x22, 0x2a, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x41, 0x6c, 0x6c, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x45, 0x0a,
	0x19, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x41, 0x6c, 0x6c, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x10, 0x62, 0x61,
	0x6e, 0x6b, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x05, 0x52, 0x0e, 0x62, 0x61, 0x6e, 0x6b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x49, 0x64, 0x73, 0x32, 0xc3, 0x02, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x67, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1f, 0x2e, 0x72, 0x47, 0x50, 0x43, 0x5f, 0x42, 0x61, 0x6e,
	0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x72, 0x47, 0x50, 0x43, 0x5f, 0x42, 0x61,
	0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x16, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x10,
	0x22, 0x0b, 0x2f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x3a, 0x01, 0x2a,
	0x12, 0x5d, 0x0a, 0x08, 0x52, 0x65, 0x61, 0x64, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1d, 0x2e, 0x72,
	0x47, 0x50, 0x43, 0x5f, 0x42, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x65, 0x61, 0x64,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x72, 0x47,
	0x50, 0x43, 0x5f, 0x42, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x12, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x0c, 0x12, 0x0a, 0x2f, 0x55, 0x73, 0x65, 0x72, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12,
	0x69, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x1f, 0x2e,
	0x72, 0x47, 0x50, 0x43, 0x5f, 0x42, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20,
	0x2e, 0x72, 0x47, 0x50, 0x43, 0x5f, 0x42, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x18, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x12, 0x12, 0x10, 0x2f, 0x55, 0x73, 0x65, 0x72, 0x72,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x32, 0xeb, 0x05, 0x0a, 0x0e, 0x42,
	0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x83, 0x01,
	0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x6e, 0x6b, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x26, 0x2e, 0x72, 0x47, 0x50, 0x43, 0x5f, 0x42, 0x61, 0x6e, 0x6b, 0x69,
	0x6e, 0x67, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x6e, 0x6b, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x72, 0x47,
	0x50, 0x43, 0x5f, 0x42, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x42, 0x61, 0x6e, 0x6b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x17, 0x22, 0x12, 0x2f, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x6e, 0x6b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x3a, 0x01, 0x2a, 0x12, 0x6a, 0x0a, 0x0c, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x4d, 0x6f,
	0x6e, 0x65, 0x79, 0x12, 0x21, 0x2e, 0x72, 0x47, 0x50, 0x43, 0x5f, 0x42, 0x61, 0x6e, 0x6b, 0x69,
	0x6e, 0x67, 0x2e, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x72, 0x47, 0x50, 0x43, 0x5f, 0x42, 0x61,
	0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x4d, 0x6f, 0x6e,
	0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x13, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x0d, 0x22, 0x08, 0x2f, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x3a, 0x01, 0x2a, 0x12,
	0x6e, 0x0a, 0x0d, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x4d, 0x6f, 0x6e, 0x65, 0x79,
	0x12, 0x22, 0x2e, 0x72, 0x47, 0x50, 0x43, 0x5f, 0x42, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x2e,
	0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x72, 0x47, 0x50, 0x43, 0x5f, 0x42, 0x61, 0x6e, 0x6b,
	0x69, 0x6e, 0x67, 0x2e, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x4d, 0x6f, 0x6e, 0x65,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x14, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x0e, 0x22, 0x09, 0x2f, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x3a, 0x01, 0x2a, 0x12,
	0x83, 0x01, 0x0a, 0x11, 0x42, 0x61, 0x6e, 0x6b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x26, 0x2e, 0x72, 0x47, 0x50, 0x43, 0x5f, 0x42, 0x61, 0x6e,
	0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x42, 0x61, 0x6e, 0x6b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e,
	0x72, 0x47, 0x50, 0x43, 0x5f, 0x42, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x42, 0x61, 0x6e,
	0x6b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x17, 0x22, 0x12,
	0x2f, 0x42, 0x61, 0x6e, 0x6b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x3a, 0x01, 0x2a, 0x12, 0x71, 0x0a, 0x10, 0x41, 0x6c, 0x6c, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x1a, 0x2e, 0x72, 0x47, 0x50, 0x43,
	0x5f, 0x42, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x72, 0x47, 0x50, 0x43, 0x5f, 0x42, 0x61, 0x6e,
	0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x41, 0x6c, 0x6c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x19, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x13, 0x12, 0x11, 0x2f, 0x41, 0x6c, 0x6c, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x7e, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x41, 0x6c, 0x6c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x26, 0x2e,
	0x72, 0x47, 0x50, 0x43, 0x5f, 0x42, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x41, 0x6c, 0x6c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x72, 0x47, 0x50, 0x43, 0x5f, 0x42, 0x61, 0x6e,
	0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x41, 0x6c, 0x6c, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x18,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x12, 0x12, 0x10, 0x2f, 0x41, 0x6c, 0x6c, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x61, 0x6e, 0x67, 0x32, 0x35, 0x32, 0x2f, 0x47,
	0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2d, 0x67, 0x52, 0x50, 0x43, 0x2d, 0x42, 0x61, 0x6e, 0x6b, 0x69,
	0x6e, 0x67, 0x3b, 0x47, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x5f, 0x67, 0x52, 0x50, 0x43, 0x5f, 0x42,
	0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Bankingpb_Golang_gRPC_Banking_proto_rawDescOnce sync.Once
	file_Bankingpb_Golang_gRPC_Banking_proto_rawDescData = file_Bankingpb_Golang_gRPC_Banking_proto_rawDesc
)

func file_Bankingpb_Golang_gRPC_Banking_proto_rawDescGZIP() []byte {
	file_Bankingpb_Golang_gRPC_Banking_proto_rawDescOnce.Do(func() {
		file_Bankingpb_Golang_gRPC_Banking_proto_rawDescData = protoimpl.X.CompressGZIP(file_Bankingpb_Golang_gRPC_Banking_proto_rawDescData)
	})
	return file_Bankingpb_Golang_gRPC_Banking_proto_rawDescData
}

var file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_Bankingpb_Golang_gRPC_Banking_proto_goTypes = []interface{}{
	(*CreateUserRequest)(nil),         // 0: rGPC_Banking.CreateUserRequest
	(*CreateUserResponse)(nil),        // 1: rGPC_Banking.CreateUserResponse
	(*ReadUserRequest)(nil),           // 2: rGPC_Banking.ReadUserRequest
	(*ReadUserResponse)(nil),          // 3: rGPC_Banking.ReadUserResponse
	(*CreateBankAccountRequest)(nil),  // 4: rGPC_Banking.CreateBankAccountRequest
	(*CreateBankAccountResponse)(nil), // 5: rGPC_Banking.CreateBankAccountResponse
	(*DepositMoneyRequest)(nil),       // 6: rGPC_Banking.DepositMoneyRequest
	(*DepositMoneyResponse)(nil),      // 7: rGPC_Banking.DepositMoneyResponse
	(*WithdrawMoneyRequest)(nil),      // 8: rGPC_Banking.WithdrawMoneyRequest
	(*WithdrawMoneyResponse)(nil),     // 9: rGPC_Banking.WithdrawMoneyResponse
	(*EmptyRequest)(nil),              // 10: rGPC_Banking.EmptyRequest
	(*BankAccountReportRequest)(nil),  // 11: rGPC_Banking.BankAccountReportRequest
	(*BankAccountReportResponse)(nil), // 12: rGPC_Banking.BankAccountReportResponse
	(*AllAccountReportResponse)(nil),  // 13: rGPC_Banking.AllAccountReportResponse
	(*UserReportRequest)(nil),         // 14: rGPC_Banking.UserReportRequest
	(*UserReportResponse)(nil),        // 15: rGPC_Banking.UserReportResponse
	(*GetUserAllAccountRequest)(nil),  // 16: rGPC_Banking.GetUserAllAccountRequest
	(*GetUserAllAccountResponse)(nil), // 17: rGPC_Banking.GetUserAllAccountResponse
}
var file_Bankingpb_Golang_gRPC_Banking_proto_depIdxs = []int32{
	12, // 0: rGPC_Banking.AllAccountReportResponse.bank_account_report:type_name -> rGPC_Banking.BankAccountReportResponse
	12, // 1: rGPC_Banking.UserReportResponse.bank_account_report:type_name -> rGPC_Banking.BankAccountReportResponse
	0,  // 2: rGPC_Banking.UserManagement.CreateUser:input_type -> rGPC_Banking.CreateUserRequest
	2,  // 3: rGPC_Banking.UserManagement.ReadUser:input_type -> rGPC_Banking.ReadUserRequest
	14, // 4: rGPC_Banking.UserManagement.UserReport:input_type -> rGPC_Banking.UserReportRequest
	4,  // 5: rGPC_Banking.BankingService.CreateBankAccount:input_type -> rGPC_Banking.CreateBankAccountRequest
	6,  // 6: rGPC_Banking.BankingService.DepositMoney:input_type -> rGPC_Banking.DepositMoneyRequest
	8,  // 7: rGPC_Banking.BankingService.WithdrawMoney:input_type -> rGPC_Banking.WithdrawMoneyRequest
	11, // 8: rGPC_Banking.BankingService.BankAccountReport:input_type -> rGPC_Banking.BankAccountReportRequest
	10, // 9: rGPC_Banking.BankingService.AllAccountReport:input_type -> rGPC_Banking.EmptyRequest
	16, // 10: rGPC_Banking.BankingService.GetUserAllAccount:input_type -> rGPC_Banking.GetUserAllAccountRequest
	1,  // 11: rGPC_Banking.UserManagement.CreateUser:output_type -> rGPC_Banking.CreateUserResponse
	3,  // 12: rGPC_Banking.UserManagement.ReadUser:output_type -> rGPC_Banking.ReadUserResponse
	15, // 13: rGPC_Banking.UserManagement.UserReport:output_type -> rGPC_Banking.UserReportResponse
	5,  // 14: rGPC_Banking.BankingService.CreateBankAccount:output_type -> rGPC_Banking.CreateBankAccountResponse
	7,  // 15: rGPC_Banking.BankingService.DepositMoney:output_type -> rGPC_Banking.DepositMoneyResponse
	9,  // 16: rGPC_Banking.BankingService.WithdrawMoney:output_type -> rGPC_Banking.WithdrawMoneyResponse
	12, // 17: rGPC_Banking.BankingService.BankAccountReport:output_type -> rGPC_Banking.BankAccountReportResponse
	13, // 18: rGPC_Banking.BankingService.AllAccountReport:output_type -> rGPC_Banking.AllAccountReportResponse
	17, // 19: rGPC_Banking.BankingService.GetUserAllAccount:output_type -> rGPC_Banking.GetUserAllAccountResponse
	11, // [11:20] is the sub-list for method output_type
	2,  // [2:11] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_Bankingpb_Golang_gRPC_Banking_proto_init() }
func file_Bankingpb_Golang_gRPC_Banking_proto_init() {
	if File_Bankingpb_Golang_gRPC_Banking_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBankAccountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBankAccountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositMoneyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositMoneyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithdrawMoneyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithdrawMoneyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BankAccountReportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BankAccountReportResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllAccountReportResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserReportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserReportResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserAllAccountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserAllAccountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Bankingpb_Golang_gRPC_Banking_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_Bankingpb_Golang_gRPC_Banking_proto_goTypes,
		DependencyIndexes: file_Bankingpb_Golang_gRPC_Banking_proto_depIdxs,
		MessageInfos:      file_Bankingpb_Golang_gRPC_Banking_proto_msgTypes,
	}.Build()
	File_Bankingpb_Golang_gRPC_Banking_proto = out.File
	file_Bankingpb_Golang_gRPC_Banking_proto_rawDesc = nil
	file_Bankingpb_Golang_gRPC_Banking_proto_goTypes = nil
	file_Bankingpb_Golang_gRPC_Banking_proto_depIdxs = nil
}
